local map = vim.api.nvim_set_keymap

map("i", "<CR>", "compe#confirm('<CR>')", { noremap = true, expr = true, silent = true })
map("i", "jk", "<Esc>", { noremap = true })
map("n", ",f", "<cmd>lua vim.lsp.buf.formatting()<cr>", { noremap = true })
map("n", "\\", "<cmd>lua require'hop'.hint_words()<cr>", { noremap = true })
map('n', '<C-p>', "<cmd>lua require'telescope.builtin'.find_files({ find_command = {'rg', '--files', '--hidden', '-g', '!.git' }})<cr>", { noremap = true, silent = true })
map("n", "<Leader><Leader>", "<cmd>noh<CR>", { noremap = true })
map("n", "<Leader>g", "<cmd>Telescope live_grep<CR>", { noremap = true })
map("n", "<Leader>b", "<cmd>Telescope buffers<CR>",  { noremap = true } )
map("n", "<Leader>w", "<cmd>up<CR>", { noremap = true })
map("n", "<Leader>d", "<cmd>pu=strftime('%b %d, %Y %X')<CR>", { noremap = true })
map("n", "<Leader>f", "<cmd>NvimTreeFindFile<cr>", { noremap = true })
map("n", "<Leader>n", "<cmd>NvimTreeToggle<cr>", { noremap = true })
map("n", "<Leader>p", "<cmd>MarkdownPreview<CR>", { noremap = true })
map("n", "<A-t>", "<cmd>FloatermToggle<CR>", { noremap = true, silent = true })
map("t", "<A-t>", "<C-\\><C-n><cmd>FloatermToggle<CR>", { noremap = true, silent = true })
map("n", "<A-g>", "<cmd>FloatermNew lazygit<CR>", { noremap = true, silent = true })
map("t", "<A-g>", "<C-\\><C-n><cmd>FloatermKill<CR>", { noremap = true, silent = true })
map("n", "<C-_>", "<Plug>NERDCommenterToggle", {})
map("v", "<C-_>", "<Plug>NERDCommenterToggle<CR>", {})
map("v", "<Leader>y", "\"+y", { noremap = true })
map("n", "<Leader>y", "\"+y", { noremap = true })
map("n", "<Leader>Y", "\"+yg_", { noremap = true })

