require("config.compe")
require("config.indentline")
require("config.lsp")
require("config.lualine")
require("config.nerd_commenter")
require("config.nvim_tree")
require("config.telescope")
require("config.treesitter")
