require("config.compe")
require("config.galaxyline")
require("config.gitsigns")
require("config.indentline")
require("config.lsp")
require("config.lspsaga")
-- require("config.lualine")
require("config.nerd_commenter")
require("config.nvim-tree")
require("config.telescope")
require("config.treesitter")
require("config.web-devicons")
