env:
  TERM: xterm-256color

font:
  size: 10.5
  normal:
    family: "MesloLGS NF"

colors:
  primary:
    background: "#282c34"
    foreground: "#abb2bf"
  cursor:
    text: CellBackground
    cursor: "#528bff" # syntax-cursor-color
  selection:
    text: CellForeground
    background: "#3e4451" # syntax-selection-color
  normal:
    black: "#5c6370" # mono-3
    red: "#e06c75" # red 1
    green: "#98c379"
    yellow: "#e5c07b" # orange 2
    blue: "#61afef"
    magenta: "#c678dd"
    cyan: "#56b6c2"
    white: "#828997" # mono-2

window:
  dimensions:
    columns: 90
    lines: 30
  padding:
    x: 10
    y: 10

  dynamic_padding: true
  decorations: none
  startup_mode: Windowed

key_bindings:
  - { key: F11, action: ToggleFullscreen }
