vim.api.nvim_set_keymap("i", "<CR>", "compe#confirm('<CR>')", { noremap = true, expr = true })
vim.api.nvim_set_keymap("n", "<Leader><Leader>", "<cmd>noh<CR>", { noremap = true })
vim.api.nvim_set_keymap("i", "jk", "<Esc>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>w", "<cmd>up<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>d", "<cmd>pu=strftime('%b %d, %Y %X')<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "\\", "<cmd>lua require'hop'.hint_words()<cr>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>f", "<cmd>NvimTreeFindFile<cr>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>n", "<cmd>NvimTreeToggle<cr>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>gs", "<cmd>Gstatus<CR>", { noremap = true })
vim.api.nvim_set_keymap('n', "<C-p>", "<cmd>Telescope git_files find_command=rg,--ignore,--hidden,--files<cr>", { noremap = true, silent = true})
vim.api.nvim_set_keymap("n", "<Leader>g", "<cmd>Telescope live_grep<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>b", "<cmd>Telescope buffers<CR>",  { noremap = true } )
vim.api.nvim_set_keymap("n", "<Leader>a", "<cmd>Lspsaga code_action<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "K", "<cmd>Lspsaga hover_doc<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "C-k", "<cmd>Lspsaga signature_help<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "gd", "<cmd>lua require'lspsaga.provider'.preview_definition()<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "gf", "<cmd>Lspsaga lsp_finder<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "ge", "<cmd>Lspsaga show_cursor_diagnostics<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "gn", "<cmd>Lspsaga diagnostic_jump_next<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "gp", "<cmd>Lspsaga diagnostic_jump_prev<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-j>", "<cmd>lua require('lspsaga.action').smart_scroll_with_saga(1)<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-k>", "<cmd>lua require('lspsaga.action').smart_scroll_with_saga(-1)<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<A-t>", "<cmd>Lspsaga open_floaterm<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("t", "<A-t>", "<C-\\><C-n><cmd>Lspsaga close_floaterm<CR>", { noremap = true, silent = true })

