vim.api.nvim_set_keymap("n", "<Leader><Leader>", "<cmd>noh<CR>", { noremap = true })
vim.api.nvim_set_keymap("i", "jk", "<Esc>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>w", "<cmd>up<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>d", "<cmd>pu=strftime('%b %d, %Y %X')<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "\\", "<cmd>lua require'hop'.hint_words()<cr>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>f", "<cmd>NvimTreeFindFile<cr>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>n", "<cmd>NvimTreeToggle<cr>", { noremap = true })
-- vim.api.nvim_set_keymap("n", "<leader>a", "<cmd>Lspsaga code_action<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>gs", "<cmd>Gstatus<CR>", { noremap = true })
vim.api.nvim_set_keymap('n', "<C-p>", "<cmd>Telescope git_files find_command=rg,--ignore,--hidden,--files<cr>", { noremap = true, silent = true})
vim.api.nvim_set_keymap("n", "<Leader>g", "<cmd>Telescope live_grep<CR>", { noremap = true })
vim.api.nvim_set_keymap("n", "<Leader>b", "<cmd>Telescope buffers<CR>",  { noremap = true } )
vim.api.nvim_set_keymap("i", "<CR>", "compe#confirm('<CR>')", { noremap = true, expr = true })

