local map = vim.keymap.set

map("i", "jk", "<Esc>", { noremap = true })
map("n", ",f", "<cmd>lua vim.lsp.buf.format({ timeout_ms = 2000 })<cr>", { noremap = true })
map("n", "\\", "<cmd>lua require'hop'.hint_words()<cr>", { noremap = true })
map("n", "<Leader><Leader>", "<cmd>noh<CR>", { noremap = true })
map("n", "<Leader>w", "<cmd>up<CR>", { noremap = true })
map("v", "<Leader>y", '"+y', { noremap = true })
map("n", "<Leader>y", '"+y', { noremap = true })
map("n", "<Leader>Y", '"+yg_', { noremap = true })
map("n", "+", "<C-a>", { noremap = true })
map("n", "-", "<C-x>", { noremap = true })
map("n", "J", "mzJ`z")
map("n", "<C-d>", "<C-d>zz")
map("n", "<C-u>", "<C-u>zz")
map("n", "n", "nzzzv")
map("n", "N", "Nzzzv")
