#! /bin/sh

chosen=$(printf "  Lock\n  Log Out\n  Sleep\n  Power Off\n  Restart" | rofi -dmenu -i)

case "$chosen" in
"  Lock") betterlockscreen -l --display 0 --span ;;
"  Log Out") i3-msg exit ;;
"  Sleep") systemctl suspend ;;
"  Power Off") poweroff ;;
"  Restart") reboot ;;
*) exit 1 ;;
esac
